# Generated by Django 4.0.6 on 2022-11-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='phoneNumber',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
