# Generated by Django 4.0.6 on 2022-11-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_advuser_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='phoneNumber',
            new_name='phone_num',
        ),
    ]
