# Generated by Django 4.0.6 on 2022-11-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_alter_advuser_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='faculty',
            field=models.CharField(blank=True, choices=[('bio', 'Биологический факультет'), ('geo', 'Геолого-географический факультет'), ('ist', 'Факультет истории и межкультурных коммуникаций'), ('in', 'Факультет иностранных языков'), ('mat', 'Факультет математитики и ТП'), ('psi', 'Факультет психологии и педагогики'), ('fiz', 'Факультет физики и ИТ'), ('ffk', 'Факультет физической культуры'), ('fil', 'Филологический факультет'), ('eko', 'Экономический факультет'), ('yr', 'Юридичесий факультет')], default='fiz', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advuser',
            name='group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='phone_num',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
