# Generated by Django 4.0.6 on 2022-11-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pubdate'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pubdate'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
