# Generated by Django 4.0.6 on 2022-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventdate',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='eventtime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
