# Generated by Django 4.0.6 on 2022-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_post_eventdate_post_eventtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventtime',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
