# Generated by Django 4.0.6 on 2022-11-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_alter_post_eventdate_alter_post_eventtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mesta',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stoim',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
