# Generated by Django 4.0.6 on 2022-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_post_mesta_post_stoim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
