# Generated by Django 4.0.6 on 2022-11-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_alter_post_mesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
