# Generated by Django 4.0.6 on 2022-11-10 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_remove_comment_audio_remove_comment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zapisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Записаные', to=settings.AUTH_USER_MODEL),
        ),
    ]
