# Generated by Django 4.0.6 on 2022-11-10 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_remove_post_zapisi_post_zapisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zapisi',
            field=models.ManyToManyField(related_name='Записаные', to=settings.AUTH_USER_MODEL),
        ),
    ]
