# Generated by Django 4.0.6 on 2022-11-14 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_post_zapisi_delete_zapisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='zapisi',
            field=models.ManyToManyField(blank=True, related_name='Записаные', to=settings.AUTH_USER_MODEL),
        ),
    ]
