# Generated by Django 4.0.6 on 2022-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_comment_moderation_alter_post_zapisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventdate', models.DateField(db_index=True, null=True)),
                ('eventtime', models.TimeField(choices=[('9', '9:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00')], db_index=True, null=True)),
            ],
        ),
    ]
