# Generated by Django 4.0.6 on 2022-11-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_consult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='eventtime',
            field=models.TimeField(choices=[('9', '9:00:00'), ('10', '10:00:00'), ('11', '11:00:00'), ('12', '12:00:00'), ('13', '13:00:00'), ('14', '14:00:00'), ('15', '15:00:00')], db_index=True, null=True),
        ),
    ]
