# Generated by Django 4.0.6 on 2022-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_alter_consult_eventtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='eventtime',
            field=models.CharField(choices=[('9', '9:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('cult', 'Культурно-досуговая деятельность'), ('sport', 'Спортивная деятельность'), ('mass', 'Массовые мероприятия и выставки'), ('trud', 'Трудовая и волонтерская деятельность')], max_length=50),
        ),
    ]
