# Generated by Django 4.0.6 on 2022-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0050_alter_consult_eventtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consult',
            options={'ordering': ['eventdate'], 'verbose_name': 'Консультация', 'verbose_name_plural': 'Консультации'},
        ),
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
