# Generated by Django 4.0.6 on 2022-11-17 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0051_alter_consult_options_alter_post_mesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.IntegerField(default=2, max_length=10, null=True, validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
