# Generated by Django 4.0.6 on 2022-11-17 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0052_alter_post_mesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Otobr', models.BooleanField(db_index=True, default=False, verbose_name='Отображение')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.IntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
