# Generated by Django 4.0.6 on 2022-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0053_section_alter_post_mesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['eventdate'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Otobr',
            new_name='otobr',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
