# Generated by Django 4.0.6 on 2022-11-18 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0054_alter_post_options_rename_otobr_section_otobr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('otobr', models.BooleanField(db_index=True, default=False, verbose_name='Отображение')),
            ],
        ),
        migrations.AlterField(
            model_name='advuser',
            name='faculty',
            field=models.CharField(choices=[('bio', 'Биологический факультет'), ('geo', 'Геолого-географический факультет'), ('ist', 'Факультет истории и межкультурных коммуникаций'), ('in', 'Факультет иностранных языков'), ('mat', 'Факультет математитики и ТП'), ('psi', 'Факультет психологии и педагогики'), ('fiz', 'Факультет физики и ИТ'), ('ffk', 'Факультет физической культуры'), ('fil', 'Филологический факультет'), ('eko', 'Экономический факультет'), ('yr', 'Юридичесий факультет')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.IntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
