# Generated by Django 4.0.6 on 2022-11-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0055_tvor_alter_advuser_faculty_alter_advuser_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('otobr', models.BooleanField(db_index=True, default=False, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Трудовое направление',
                'verbose_name_plural': 'Трудовые направления',
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция', 'verbose_name_plural': 'Секции'},
        ),
        migrations.AlterModelOptions(
            name='tvor',
            options={'verbose_name': 'Творческое направление', 'verbose_name_plural': 'Творческие направления'},
        ),
    ]
