# Generated by Django 4.0.6 on 2022-11-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0056_trud_alter_section_options_alter_tvor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('otobr', models.BooleanField(db_index=True, default=False, verbose_name='Отображение')),
            ],
            options={
                'verbose_name': 'Волонтерское направление',
                'verbose_name_plural': 'Волонтерские направления',
            },
        ),
    ]
