# Generated by Django 4.0.6 on 2022-11-21 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0059_alter_vist_options_rename_pubdate_vist_pdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vist',
            name='pdate',
        ),
    ]
