# Generated by Django 4.0.6 on 2022-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0061_rename_eventdate_vist_enddate_vist_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vist',
            name='zapisiv',
        ),
        migrations.AddField(
            model_name='vist',
            name='zanv',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Занято'),
        ),
    ]
