# Generated by Django 4.0.6 on 2022-11-22 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0064_post_vist_delete_vist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vist',
        ),
        migrations.CreateModel(
            name='Vist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/')),
                ('pubdate', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publication date')),
                ('eventtime', models.TimeField(db_index=True, null=True)),
                ('eventdate', models.DateField(db_index=True, null=True)),
                ('stoim', models.CharField(max_length=10, null=True)),
                ('zanv', models.BooleanField(db_index=True, default=False, verbose_name='Выставка')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'ordering': ['eventdate'],
            },
        ),
    ]
