# Generated by Django 4.0.6 on 2022-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0065_remove_post_vist_vist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vist',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Выставка'),
        ),
        migrations.DeleteModel(
            name='Vist',
        ),
    ]
