# Generated by Django 4.0.6 on 2022-11-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0067_event_remove_post_vist_vist_comment_vist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.vist'),
        ),
    ]
