# Generated by Django 4.0.6 on 2022-11-23 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0068_alter_comment_post_alter_comment_vist'),
    ]

    operations = [
        migrations.AddField(
            model_name='vist',
            name='zapisi',
            field=models.ManyToManyField(blank=True, related_name='Записи', to=settings.AUTH_USER_MODEL),
        ),
    ]
