# Generated by Django 4.0.6 on 2022-11-23 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0069_vist_zapisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vist',
            name='zapisi',
        ),
        migrations.AddField(
            model_name='event',
            name='zapisi',
            field=models.ManyToManyField(blank=True, related_name='Записи', to=settings.AUTH_USER_MODEL),
        ),
    ]
