# Generated by Django 4.0.6 on 2022-11-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0070_remove_vist_zapisi_event_zapisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vist',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='vist',
            field=models.ManyToManyField(blank=True, related_name='Мероприятия', to='news.vist'),
        ),
    ]
