# Generated by Django 4.0.6 on 2022-11-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0071_remove_vist_event_event_vist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='vist',
        ),
        migrations.AddField(
            model_name='vist',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='Даты', to='news.event'),
        ),
    ]
