# Generated by Django 4.0.6 on 2022-12-02 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0072_remove_event_vist_vist_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Время и дата выставки', 'verbose_name_plural': 'Время и дата выставки'},
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Групповая'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='faculty',
            field=models.CharField(choices=[('bio', 'Биологический факультет'), ('geo', 'Геолого-географический факультет'), ('ist', 'Факультет истории и межкультурных коммуникаций'), ('in', 'Факультет иностранных языков'), ('mat', 'Факультет математитики и ТП'), ('psi', 'Факультет психологии и педагогики'), ('fiz', 'Факультет физики и ИТ'), ('ffk', 'Факультет физической культуры'), ('fil', 'Филологический факультет'), ('eko', 'Экономический факультет'), ('yr', 'Юридичесий факультет')], max_length=50, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='group',
            field=models.CharField(max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацию'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='phone_num',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='vist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.vist', verbose_name='Выставка'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='eventdate',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='eventtime',
            field=models.CharField(choices=[('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00')], max_length=10, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='zan',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdate',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventtime',
            field=models.TimeField(db_index=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zapisi',
            field=models.ManyToManyField(blank=True, related_name='Записи', to=settings.AUTH_USER_MODEL, verbose_name='Записаные'),
        ),
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventdate',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='eventtime',
            field=models.TimeField(db_index=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Приклепленные файлы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mesta',
            field=models.IntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='stoim',
            field=models.CharField(max_length=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('cult', 'Культурно-досуговая деятельность'), ('sport', 'Спортивная деятельность'), ('mass', 'Массовые мероприятия и выставки'), ('trud', 'Трудовая и волонтерская деятельность')], max_length=50, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zapisi',
            field=models.ManyToManyField(blank=True, related_name='Записаные', to=settings.AUTH_USER_MODEL, verbose_name='Записаные'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='trud',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tvor',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='content',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='Даты', to='news.event', verbose_name='Время и дата'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Приклепленные файлы'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='stoim',
            field=models.CharField(max_length=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='vist',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='volant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
