# Generated by Django 4.0.6 on 2022-12-02 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0073_alter_event_options_event_group_alter_advuser_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_zap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typezap', models.CharField(max_length=10, null=True, verbose_name='Группа')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
