# Generated by Django 4.0.6 on 2022-12-02 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0073_alter_event_options_event_group_alter_advuser_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='zapisi',
        ),
        migrations.CreateModel(
            name='Zapis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.BooleanField(db_index=True, default=False, verbose_name='Групповая')),
                ('zap', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Записаные')),
            ],
            options={
                'verbose_name': 'Запись на событие',
                'verbose_name_plural': 'Записи на события',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='zapis',
            field=models.ManyToManyField(blank=True, related_name='Записаные', to='news.zapis', verbose_name='Записаные'),
        ),
    ]
