# Generated by Django 4.0.6 on 2022-12-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0074_type_zap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_zap',
        ),
    ]
