# Generated by Django 4.0.6 on 2022-12-05 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0074_remove_post_zapisi_zapis_post_zapis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventtime',
            field=models.TimeField(choices=[('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00')], db_index=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zapis',
            field=models.ManyToManyField(blank=True, related_name='Записаные', to=settings.AUTH_USER_MODEL, verbose_name='Записаные'),
        ),
        migrations.DeleteModel(
            name='Zapis',
        ),
    ]
