# Generated by Django 4.0.6 on 2022-12-05 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0075_alter_event_eventtime_alter_post_zapis_delete_zapis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mesta_now',
            field=models.IntegerField(default=2, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество мест'),
        ),
    ]
